MaxItems: 10000000  # max number of item in cache  # Must be depracated
DefaultTTL: 6w #10s, 3m, 6h, 7d, 2w, 3M, 1y 
SyncTime: 30m # interval to sync cache on disk (may be slow)
SyncFile: /var/lib/go-cache/data.bin    # file to sync cache
LogFile: /var/log/cache/go-cache.log  # use /dev/null to disable 
HTTP:
    Ip:  0.0.0.0 #listen ip 0.0.0.0 to listen all ifaces
    Port: 9001
    SSL: false
    Crt: ""
    Key: ""
    Allow:
        - 127.0.0.1   
        - 10.20.5.6
        - 10.255.128.0/24
        - 195.211.250.0/24
    Deny:
